Lesson2
TrishinIN/HomeWork1 pull request #2
Opened 2021-04-18 20:48 UTC by TrishinIN

HomeWork2

2021-04-19 17:25 UTC, TrishinIN commented on Lesson2/Lesson2.java
> +        if (i == 400) {
Перепутал условие. Верно i % 400 ==0

2021-04-20 06:36 UTC, OKrylov requested changes
В целом все хорошо, но обратите внимание на замечания

2021-04-20 06:36 UTC, OKrylov commented on Lesson2/Lesson2.java
> +        if (a + b >= 10 && a + b <= 20) {
можно результат суммирования вынести в отдельную переменную, чтобы не вычислять его дважды

2021-04-20 06:36 UTC, OKrylov commented on Lesson2/Lesson2.java
> +    public static void print(int a, String b) {
> Метод должен вернуть true, если число отрицательное, и вернуть false если положительное.

Имелось ввиду, что мы должны вернуть из метода логическое значение путём использования return

2021-04-20 06:36 UTC, OKrylov commented on Lesson2/Lesson2.java
> +    public static void year(int i) {
> и возвращает boolean

Вместо Syste.out нужно было использовать return

2021-04-21 14:20 UTC, merged